### ISSUE TITLE
Replace `IsActive` with `ActivePeriodStart` and `ActivePeriodEnd`

### ISSUE THREAD

**Issue by JustRoxy** [stanriders/circleforms#134]
Don't think this should be editable? We should replace this with `DateTime? ActivePeriodStart` and `DateTime? ActivePeriodEnd` later

_Originally posted by @stanriders in https://github.com/stanriders/circleforms/pull/130#discussion_r860978677_

**Comment by stanriders** [comment]
Resolved by #138
